TicketOffice/Models/Route.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace TicketOffice.Models;

public class Route
{
    [Key]
    [BindRequired]
    public int Id { get; set; }

    [Required(ErrorMessage = "Поле має бути заповненим")]
    [Display(Name = "Номер")]
    [Range(1, 9999)]
    public int Number { get; set; }
    
    [Required(ErrorMessage = "Поле має бути заповненим")]
    [Display(Name = "Ємність")]
    [Range(5, 40)]
    public int Capacity { get; set; }
    
    [Required]
    public List<RouteCity> Cities { get; set; } = null!;

    public List<Ticket>? Tickets { get; set; }
    
    public double GetTotalCost()
    {
        double cost = 0;

        for (int i = 1; i < Cities.Count; i++)
        {
            cost += Cities.ToList()[i].CostFromPreviousCity ?? 0;
        }

        return cost;
    }
}

TicketOffice/Pages/Management/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TicketOffice.Services;

namespace TicketOffice.Pages.Management;

public class Index : PageModel
{
    private readonly UserValidationService validationService;

    public Index(UserValidationService validationService)
    {
        this.validationService = validationService;
    }
    
    public ActionResult OnGet()
    {
        if (!validationService.IsAuthorized(HttpContext))
        {
            return RedirectToPage("/Index");
        }
        else
        {
            return RedirectToPage("./Routes");
        }
    }
}

TicketOffice/Pages/Management/Routes/Create.cshtml.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TicketOffice.Data;
using TicketOffice.Models;
using TicketOffice.Services;
using Route = TicketOffice.Models.Route;

namespace TicketOffice.Pages.Management.Routes;

public class CreateModel : PageModel
{
    // Error massage displaying when route number validation failed.
    public string NumberValidationError = null!;
    
    // Error massage displaying when route capacity validation failed.
    public string CapacityValidationError = null!;
    
    // Array of error massages displaying when route name validation failed.
    public string[] NameValidationError = null!;
    
    // Array of error massages displaying when cities
    // departure time validation failed.
    public string[] DepartureTimeValidationError = null!;
    
    // Array of error massages displaying when cities
    // arrival time validation failed.
    public string[] ArrivalTimeValidationError = null!;
    
    private readonly TicketOfficeContext context;
    private readonly UserValidationService validationService;

    public CreateModel(TicketOfficeContext context,
        UserValidationService validationService)
    {
        this.context = context;
        this.validationService = validationService;
    }

    // Object representing that will be created.
    [BindProperty]
    public Route Route { get; set; } = null!;

    // Object holding cities' arrival/departure dates.
    [BindProperty]
    public DateString[] TimeStrings { get; set; } = null!;

    // Amount of cities to be added to the route
    [BindProperty]
    public int? CitiesCount { get; set; }
    
    // Called when GET request is sent to the page.
    public IActionResult OnGet()
    {
        if (!validationService.IsManager(HttpContext))
        {
            return RedirectToPage("/Index");
        }
        
        return Page();
    }

    // Called when POST request is sent to the page (when user tries to add new
    // route). Validates input, creates new route in the database and
    // redirects to "Management/Routes" page.
    public ActionResult OnPost()
    {
        if (CitiesCount != null)
        {
            Route = new Route();
            Route.Cities = new List<RouteCity>();
            
            TimeStrings = new DateString[(int) CitiesCount];
            for (int i = 0; i < CitiesCount; i++)
            {
                TimeStrings[i] = new DateString();
                Route.Cities.Add(new RouteCity());
            }
            
            NameValidationError = new string[(int) CitiesCount];
            DepartureTimeValidationError = new string[(int) CitiesCount];
            ArrivalTimeValidationError = new string[(int) CitiesCount];
            
            return Page();
        }
        
        NameValidationError = new string[Route.Cities.Count];
        DepartureTimeValidationError = new string[Route.Cities.Count];
        ArrivalTimeValidationError = new string[Route.Cities.Count];
        
        InsertDatesIntoCities();

        if (!ValidateInput())
        {
            return Page();
        }

        context.Route.Add(Route);
        context.SaveChanges();

        return RedirectToPage("./Index");
    }

    private void InsertDatesIntoCities()
    {
        for (int i = 0; i < Route.Cities.Count; i++)
        {

            try
            {
                Route.Cities[i].DepartureTime =
                    ConvertStringToDate(TimeStrings[i].DepartureDate!);
            }
            catch(Exception)
            {
                if (Route.Cities.Count > 2)
                {
                    InitializeArray<string>(DepartureTimeValidationError,
                        Route.Cities.Count, 
                        "");
                }
                
                DepartureTimeValidationError[i] = "Формат: dd.MM.yyyy, hh:mm";
            }
            
            try
            {
                Route.Cities[i].ArrivalTime =
                    ConvertStringToDate(TimeStrings[i].ArrivalDate!);
            }
            catch(Exception)
            {
                if (Route.Cities.Count > 2)
                {
                    InitializeArray<string>(ArrivalTimeValidationError,
                        Route.Cities.Count, 
                        "");
                }
                
                ArrivalTimeValidationError[i] = "Формат: dd.MM.yyyy, hh:mm";
            }
        }
        
        DateTime? ConvertStringToDate(string dateStr)
        {
            if (String.IsNullOrWhiteSpace(dateStr) ||
                String.IsNullOrEmpty(dateStr))
            {
                return null;
            }

            if (dateStr.Count(c => c == '.') != 2 &&
                dateStr.Count(c => c == ':') != 2 &&
                dateStr.Count(c => c == ',') != 1)
            {
                throw new ArgumentException("Invalid input format");
            }
            
            string[] date = dateStr.Split(",")[0].Split(".");
            string[] time = dateStr.Split(",")[1].Split(":");
            
            date.ToList().ForEach(s => s.Trim());
            time.ToList().ForEach(s => s.Trim());

            return new DateTime(
                Int32.Parse(date[2]),
                Int32.Parse(date[1]),
                Int32.Parse(date[0]),
                Int32.Parse(time[0]),
                Int32.Parse(time[1]),
                0);
        }
    }

    private bool ValidateInput()
    {
        bool isValidNumber = ValidateNumber(Route.Number, out NumberValidationError);

        bool isValidCapacity = ValidateCapacity(Route.Capacity, out CapacityValidationError);

        for (int i = 0; i < Route.Cities.Count; i++)
        {
            if (Route.Cities.Count > 2)
            {
                InitializeArray<string>(NameValidationError,
                    Route.Cities.Count,
                    "");
            }
            
            ValidateName(Route.Cities[i].Name, out NameValidationError[i]);
        }
        
        for (int i = 0; i < Route.Cities.Count; i++)
        {
            if (Route.Cities.Count > 2)
            {
                InitializeArray<string>(DepartureTimeValidationError,
                    Route.Cities.Count, 
                    "");
            }
            
            ValidateDate(Route.Cities[i].DepartureTime, out DepartureTimeValidationError[i]);
        }
        
        for (int i = 0; i < Route.Cities.Count; i++)
        {
            if (Route.Cities.Count > 2)
            {
                InitializeArray<string>(ArrivalTimeValidationError,
                    Route.Cities.Count, 
                    "");
            }
            
            ValidateDate(Route.Cities[i].ArrivalTime, out ArrivalTimeValidationError[i]);
        }

        if (!isValidNumber || !isValidCapacity ||
            NameValidationError.Any(e => e != "") ||
            DepartureTimeValidationError.Any(e => e != "") ||
            ArrivalTimeValidationError.Any(e => e != ""))
        {
            return false;
        }
        
        return true;
        
        bool ValidateNumber(int number, out string validationError)
        {
            validationError = "";
            
            if (number < 1 || number > 9999)
            {
                validationError = "Має бути в проміжку від 1 до 9999";
                return false;
            }
            
            return true;
        }

        bool ValidateCapacity(int capacity, out string validationError)
        {
            validationError = "";
            
            if (capacity < 1 || capacity > 40)
            {
                validationError = "Має бути в проміжку від 5 до 45";
                return false;
            }
            
            return true;
        }

        bool ValidateName(string name, out string validationError)
        {
            validationError = "";
            
            if (String.IsNullOrWhiteSpace(name) || String.IsNullOrEmpty(name))
            {
                validationError = "Поле має бути заповненим";
                return false;
            }
            
            return true;
        }
        
        bool ValidateDate(DateTime? date, out string validationError)
        {
            validationError = "";
            
            if (date == null)
            {
                return true;
            }
            
            if (date < DateTime.Today)
            {
                validationError = $"Має бути не раніше ніж {DateTime.Today.ToString(CultureInfo.GetCultureInfo("uk-UA")).Split(" ")[0]}";
                return false;
            }
            
            return true;
        }
    }
    
    private void InitializeArray<T>(T[] arr, int length, T initVal)
    {
        arr = new T[length];

        for (int i = 0; i < length; i++)
        {
            arr[i] = initVal;
        }
    }
}

TicketOffice/Pages/Management/Routes/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TicketOffice.Data;
using TicketOffice.Models;
using TicketOffice.Services;
using Route = TicketOffice.Models.Route;

namespace TicketOffice.Pages.Management.Routes
{
    public class IndexModel : PageModel
    {
        private readonly TicketOfficeContext context;
        private readonly UserValidationService validationService;

        public IndexModel(TicketOfficeContext context,
            UserValidationService validationService)
        {
            this.context = context;
            this.validationService = validationService;
        }

        public List<Route>? Routes { get; set; }

        // Search condition: route number.
        [BindProperty(SupportsGet = true)]
        public int? Number { get; set; }
        
        // Search condition: departure city.
        [BindProperty(SupportsGet = true)]
        public string? From { get; set; }

        // Search condition: arrival city.
        [BindProperty(SupportsGet = true)]
        public string? To { get; set; }

        // Search condition: departure date.
        [BindProperty(SupportsGet = true)]
        public DateTime? Date { get; set; }

        // Called when GET request is sent to the page.
        // Retrieves routes based on search conditions.
        public ActionResult OnGet()
        {
            if (!validationService.IsManager(HttpContext))
            {
                return RedirectToPage("/Index");
            }
            
            RetrieveAllRoutes();
            FilterRoutesByNumber();
            FilterRoutesByFrom();
            FilterRoutesByTo();
            FilterRoutesByDate();

            return Page();
        }
        
        // Called when user confirms route deletion.
        public ActionResult OnGetDeleteRoute(int deleteRouteId)
        {
            OnGet();

            Route? deleteRoute = context.Route.Find(deleteRouteId);

            if (deleteRoute != null)
            {
                context.Remove(deleteRoute);
                context.SaveChanges();
                return RedirectToPage("./Index");
            }
        
            return NotFound();
        }
        
        private void RetrieveAllRoutes()
        {
            Routes = context.Route
                .Include(r => r.Cities)
                .Include(r => r.Tickets)
                .ToList();
        }

        private void FilterRoutesByNumber()
        {
            if (Number == null || Number < 1)
            {
                return;
            }
            
            Routes!.RemoveAll(r => r.Number != Number);
        }
        
        private void FilterRoutesByFrom()
        {
            if (String.IsNullOrWhiteSpace(From) || String.IsNullOrEmpty(From))
            {
                return;
            }
            
            Routes!.RemoveAll(r => r.Cities.All(c => c.Name != From));
        }

        private void FilterRoutesByTo()
        {
            if (String.IsNullOrWhiteSpace(To) || String.IsNullOrEmpty(To))
            {
                return;
            }
            
            Routes!.RemoveAll(r => r.Cities.All(c => c.Name != To));
        }

        private void FilterRoutesByDate()
        {
            if (Date == null)
            {
                return;
            }

            Routes!.RemoveAll(r => 
                r.Cities.All(c => 
                    c.DepartureTime?.Date != Date?.Date && 
                    c.ArrivalTime?.Date != Date?.Date));
        }
    }
}

TicketOffice/Pages/Management/Routes/Create.cshtml
@page
@model TicketOffice.Pages.Management.Routes.CreateModel
@{
    ViewData["Title"] = "Створити Маршрут";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/Management/Create.css"/>

<div class="wrapper">
    
    <form method="post">
        <div class="header">
            Створити рейс
        </div>
        
        <div class="field">
            <input class="field" type="number" placeholder="Номер автобуса" min="1" max="9999" autocomplete="off" asp-for="Route.Number"/>
            <div class="validation-error"><span>@Model.NumberValidationError</span></div>
        </div>

        <div class="field">
            <input class="field" type="number" placeholder="Ємність" min="5" max="40" autocomplete="off" asp-for="Route.Capacity"/>
            <div class="validation-error"><span>@Model.CapacityValidationError</span></div>
        </div>
        
        @if (Model.CitiesCount != null)
        {
            <h2>Маршрут</h2>
            
            @for (int i = 0; i < Model.CitiesCount; i++)
            {
                <div class="new-city">
                    <div class="city-name">
                        <input class="field-city" type="text" placeholder="Назва" autocomplete="off" asp-for="Route.Cities[i].Name">
                        <div class="validation-error"><span>@Model.NameValidationError[i]</span></div>
                    </div>
                
                    <div class="city-date">
                        <input class="field-city" type="text" placeholder="Дата прибуття" autocomplete="off" asp-for="TimeStrings[i].ArrivalDate">
                        <div class="validation-error"><span></span>@Model.ArrivalTimeValidationError[i]</div>
                    </div>
                
                    <div class="city-date">
                        <input class="field-city" type="text" placeholder="Дата відправлення" autocomplete="off" asp-for="TimeStrings[i].DepartureDate">
                        <div class="validation-error"><span>@Model.DepartureTimeValidationError[i]</span></div>
                    </div>
                    
                    <div class="city-cost">
                        <input class="field-city" type="number" placeholder="Ціна" autocomplete="off" value="" min="0" asp-for="Route.Cities[i].CostFromPreviousCity">
                        @* <div class="validation-error"><span>@Model.DepartureTimeValidationError[i]</span></div> *@
                    </div>
                </div>
            }
            
            <input class="submit-btn" type="submit" value="Створити"/>
            
            <input class="field-city" type="number" value="" hidden asp-for="CitiesCount">
        }
        else
        {
            <h2>Маршрут</h2>
            
            <div class="field">
                <input class="field-city" type="number" placeholder="Скільки міст буде у маршруті" autocomplete="off" asp-for="CitiesCount">
            </div>
            <br>
            
            <input class="submit-btn" type="submit" value="Додати"/>
        }

        <div class="hint">
            <a href="./Index" class="link">Назад до Списку</a>
        </div>
    </form>
    
</div>

<script>

    let i = 1;
    
    function AddCity() {
        i++;
        
        // TODO
        // Validatio in java inserted code must be added
        
        document.getElementById('add-city-btn').insertAdjacentHTML('beforebegin',
            `<div class="new-city" id="new-city-${i}">
                 <div class="city-name">
                     <input class="field-city" type="text" placeholder="Назва" autocomplete="off" asp-for="Route.Cities[${i}].Name">
                     <div class="validation-error"><span></span></div>
                 </div>
                 
                 <div class="city-date">
                     <input class="field-city" type="text" placeholder="Дата й час прибуття" autocomplete="off" asp-for="TimeStrings[${i}].ArrivalDate">
                     <div class="validation-error"><span></span></div>
                 </div>
                 
                 <div class="city-date">
                     <input class="field-city" type="text" placeholder="Дата й час відправлення" autocomplete="off" asp-for="TimeStrings[${i}].DepartureDate">
                     <div class="validation-error"><span></span></div>
                 </div>
                 
                 <a class="link-btn" id="close-city-${i}" onclick="RemoveCity(${i})">x</a>
             </div>`)
        
        document.getElementById(`close-city-${i - 1}`).remove();
    }
    
    function RemoveCity(j) {
        document.getElementById(`new-city-${j}`).remove();
        
        i--;
        
        document.getElementById(`new-city-${i}`).insertAdjacentHTML('beforeend',
            `<a class="link-btn" id="close-city-${i}" onclick="RemoveCity(${i})">x</a>`);
    }

</script>

TicketOffice/Pages/Management/Routes/Edit.cshtml
@page
@model TicketOffice.Pages.Management.Routes.EditModel

@{
    ViewData["Title"] = $"Редагування Маршруту";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/Management/Create.css"/>

<div class="wrapper">
    
    <form method="post">
        <div class="header">
            Редагування рейсу
        </div>
        
        <div class="field">
            <input class="field" type="number" placeholder="Номер автобуса" min="1" max="9999" autocomplete="off" asp-for="Route.Number"/>
            <div class="validation-error"><span>@Model.NumberValidationError</span></div>
        </div>

        <div class="field">
            <input class="field" type="number" placeholder="Ємність" min="5" max="40" autocomplete="off" asp-for="Route.Capacity"/>
            <div class="validation-error"><span>@Model.CapacityValidationError</span></div>
        </div>
        
        <h2>Маршрут</h2>
        
        @for (int i = 0; i < @Model.Route.Cities.Count; i++)
        {
            <div class="new-city">
                <div class="city-name">
                    <input class="field-city" type="text" placeholder="Назва" autocomplete="off" asp-for="Route.Cities[i].Name">
                    <div class="validation-error"><span>@Model.NameValidationError[i]</span></div>
                </div>
            
                <div class="city-date">
                    <input class="field-city" type="text" placeholder="Дата прибуття" autocomplete="off" asp-for="TimeStrings[i].ArrivalDate">
                    <div class="validation-error"><span></span>@Model.ArrivalTimeValidationError[i]</div>
                </div>
            
                <div class="city-date">
                    <input class="field-city" type="text" placeholder="Дата відправлення" autocomplete="off" asp-for="TimeStrings[i].DepartureDate">
                    <div class="validation-error"><span>@Model.DepartureTimeValidationError[i]</span></div>
                </div>
                
                <div class="city-cost">
                    <input class="field-city" type="number" placeholder="Ціна" autocomplete="off" min="0" asp-for="Route.Cities[i].CostFromPreviousCity">
                    @* <div class="validation-error"><span>@Model.DepartureTimeValidationError[i]</span></div> *@
                </div>
                
                <input type="number" hidden value="@Model.Route.Cities[i].Id" asp-for="CityIds[i]">
            </div>
        }
        
        <input class="submit-btn" type="submit" value="Зберегти"/>
        
        <div class="hint">
            <a href="./Index" class="link">Назад до Списку</a>
        </div>
    </form>
    
</div>


TicketOffice/Pages/Management/Routes/Index.cshtml
@page
@model TicketOffice.Pages.Management.Routes.IndexModel
@{
    ViewData["Title"] = "Управління Маршрутами";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/Management/Index.css"/>
<link rel="stylesheet" href="~/css/CityListPopup.css"/>
<link rel="stylesheet" href="~/css/InfoPopup.css">

<div class="wrapper">
    
    <form class="search-block">
            <div class="opt">
                <div class="number">
                     <div class="title">
                         № автобуса
                     </div>
                    <input class="search-input" type="number" min="1" max="9999" autocomplete="off" asp-for="Number">
                </div>
                
                <div class="station">
                    <div class="title">
                        Звідки
                    </div>
                    <input class="search-input" type="text" autocomplete="off" asp-for="From">
                </div>
                
                <div class="station">
                    <div class="title">
                        Куди
                    </div>
                    <input class="search-input" type="text" autocomplete="off" asp-for="To">
                </div>
                
                <div class="date">
                    <div class="title">
                        Дата рейсу
                    </div>
                    <input class="search-input" type="date" autocomplete="off" asp-for="Date">
                </div>
                
                <div class="search-btn">
                    <input type="submit" class="search-btn" value="Пошук"/>
                </div>
            </div>
        </form>
   
    <p>
        <a class="link-btn" asp-page="Create">Створити новий</a>
    </p>

    @if (Model.Routes != null && Model.Routes.Count > 0)
    {
        <table>
            <thead>
                <tr>
                    <th>
                        № автобуса
                    </th>
                    <th>
                        Ємність автобуса
                    </th>
                    <th>
                        Квитків продано
                    </th>
                    <th>
                        Дата відправлення
                    </th>
                    <th>
                        Дії
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var route in Model.Routes) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => route.Number)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => route.Capacity)
                        </td>
                        <td>
                            @route.Tickets.Count
                        </td>
                        <td>
                            @route.Cities.First().DepartureTime.Value.ToString("dd.MM.yyyy")
                        </td>
                        <td>
                            <a class="link-btn" onclick="document.getElementById('popup-city-list-@route.Id').style.display = 'inherit'">Маршрут</a> 
                            <a class="link-btn" asp-page="./Edit" asp-route-id="@route.Id">Редагувати</a> 
                            <a class="link-btn" onclick="document.getElementById ('popup-info-@route.Id').style.display = 'inherit'">Видалити</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="search-error">
            <p>Маршрутів не знайдено. Перевірте критерії пошуку або додайте новий рейс</p>
        </div>
    }

    @if (Model.Routes != null)
    {
        foreach (var route in Model.Routes)
        {
            <div class="popup-container-city-list" id="popup-city-list-@route.Id">
                <div class="popup-city-list">
                    <div class="popup-header-city-list">
                        Рейс №@route.Number
                    </div>
                    <div class="popup-body-city-list">
                        <table class="city-list">
                            <thead>
                            <tr class="tr-intermediate city-list">
                                <th class="th-route city-list">
                                    Інформація
                                </th>
                                <th class="th-route city-list">
                                    Місто
                                </th>
                                <th class="th-route city-list">
                                    Час прибуття
                                </th>
                                <th class="th-route city-list">
                                    Час відправлення
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="tr-departure city-list">
                                <td class="td-route city-list">
                                    Відправлення
                                </td>
                                <td class="td-route city-list">
                                    @route.Cities.First().Name
                                </td>
                                <td class="td-route city-list">
                                    -
                                </td>
                                <td class="td-route city-list">
                                    @route.Cities.First().DepartureTime?.ToString("HH:mm")
                                </td>
                            </tr>
                            
                            @for (int i = 1; i < route.Cities.Count - 1; i++)
                            {
                                <tr class="tr-intermediate city-list">
                                    <td class="td-route city-list">
                                        Проміжна станція
                                    </td>
                                    <td class="td-route city-list">
                                        @route.Cities.ToList()[i].Name
                                    </td>
                                    <td class="td-route city-list">
                                        @route.Cities.ToList()[i].ArrivalTime?.ToString("HH:mm")
                                    </td>
                                    <td class="td-route city-list">
                                        @route.Cities.ToList()[i].DepartureTime?.ToString("HH:mm")
                                    </td>
                                </tr>
                            }
                            
                            <tr class="tr-arrival city-list">
                                <td class="td-route city-list">
                                    Прибуття
                                </td>
                                <td class="td-route city-list">
                                    @route.Cities.Last().Name
                                </td>
                                <td class="td-route city-list">
                                    @route.Cities.Last().ArrivalTime?.ToString("HH:mm")
                                </td>
                                <td class="td-route city-list">
                                    -
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="popup-footer-city-list">
                        <a class="popup-footer-link-button-city-list" onclick="document.getElementById('popup-city-list-@route.Id').style.display = 'none'">Закрити</a>
                    </div>
                </div>
            </div>
            
            <div class="popup-container-info" id="popup-info-@route.Id">
                <div class="popup-info">
                    <div class="popup-info-header">Рейс № @route.Number</div>
                    <div class="popup-info-body">
                        Ви дійсно хочете видалити рейс?
                    </div>
                    <div class="popup-info-footer">
                        <a class="popup-info-footer-link-button" 
                        onclick="document.getElementById('popup-info-@route.Id').style.display = 'none'">Відмінити</a>
                        <a class="popup-info-footer-link-button" asp-page-handler="DeleteRoute" asp-route-DeleteRouteId="@route.Id">Видалити</a>
                    </div>
                </div>
            </div>
        }
    }

</div>